// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package repository

type CreateUserResult struct {
	Token  string `json:"token"`
	Status string `json:"status"`
	Error  string `json:"error"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResult struct {
	Token  string `json:"token"`
	Status string `json:"status"`
	Error  string `json:"error"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type RefreshTokenResult struct {
	Token  string `json:"token"`
	Status string `json:"status"`
	Error  string `json:"error"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
